---
title: 
author: 
date:
header-includes:
   - \usepackage[brazil, english, portuguese]{babel}
   - \usepackage[utf8]{inputenc}
   - \usepackage[T1]{fontenc}
 
   - \usepackage{amsfonts}
   - \usepackage{amsmath}
   - \usepackage{amssymb}
output: 
  pdf_document:
    number_sections: false
    fig_caption: true
fontsize: 12pt
documentclass: article
---

\begin{titlepage} 
\begin{center} 

{\bf \huge Trabalho de Análise Numérica}\\
\end{center}

\begin{center}
{\large Gabriel Passos 172351}\\[0.2cm]
{\large Giovana Marques 197908}\\[0.2cm]
{\large João Luiz 199657}\\[0.2cm]
{\large Vinícius Martins 206853}\\[2cm]
\end{center}

\begin{center}
{\large Universidade Estadual de Campinas}\\[0.2cm] 
{\large Instituto de Matemática Estatística e Computação Científica}\\[0.2cm] 
{\large Professor Maicon Ribeiro Correa}\\[10.5cm]
{\large Campinas}\\[0.2cm]
{\large 2019}
\end{center}
\end{titlepage}

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE,
  warning = FALSE,
  tidy.opts = list(width.cutoff = 60),
  tidy = TRUE
  )
options(OutDec = ",", 
  digits = 3, 
  xtable.comment = FALSE
  )
```


\newpage

# Resumo

<!--colocar nome do artigo escolhido e resumir o que o artigo faz -->

# Introdução

<!--falar sobre contexto e estado da arte do artigo. Falar sobre a téecnica do artigo que sera explorada no trabalho.-->

Neste trabalho implementamos os algoritmos de Cholesky, Gram-Shmidt e QR por Rotações de Givens, os quais são utilizados para resolver sistemas lineares. Fizemos os testes nas matrizes de hilbert de ordens 3, 6 e 10. Por exemplo 
\begingroup
\setlength\arraycolsep{2pt}
$$
H_3 =
\begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3}\\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4}\\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5}
\end{bmatrix}
$$

# Algoritmos

A Decomposição de Cholesky fatora uma matriz positiva-definida e simétrica em uma matriz triangular inferior e uma triangular superior da forma $A=LL^T$, onde $L$ possui elementos na diagonal todos positivos, o que torna a decomposição única.

O algoritmo de Gram-Shmidt Clássico realiza a decomposição $A=QR$, em que $A\in \mathbb{R}^{m\times n}$, $Q\in\mathbb{R}^{m\times n}$ e $R\in\mathbb{R}^{n\times n}$ triangular superior.

A Rotação de Givens decompõe $A=QR$ zerando um elemento a cada rotação de forma a obter $Q\in\mathbb{R}^{m\times m}$ ortogonal e $R\in\mathbb{R}^{m\times n}$ triangular superior.

# Simulação

<!-- explicar como os dados foram simulados -->

# Resuldados

<!-- coloque os resultados da reproduçao do artigo via simulaçao-->

# Referências

<!--
\bibliography{bibliography}
\bibliographystyle{plain}
-->